version: '3.5'

services:
  express_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: express_api
    user: node
    working_dir: /home/node/app/api
    volumes:
      - ./:/home/node/app
    depends_on:
      - database
    env_file:
      - ./api/.env
  react_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react_client
    working_dir: /home/node/app/client
    volumes:
      - ./:/home/node/app
    env_file:
      - ./client/.env
  database:
    image: onjin/alpine-postgres:9.6
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - ./api/.env
volumes:
  database:

networks:
  default:
    external:
      name: service-tier