version: '3.5'

services:
  express_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: express_api
    user: node
    working_dir: /home/node/app/api
    volumes:
      - ${LOCAL_API_PATH}:/home/node/app
    ports:
      - ${API_PORT}:80
    depends_on:
      - database
    env_file:
      - ./api/deploy/.env
  react_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react_client
    working_dir: /home/node/app/client
    volumes:
      - ${LOCAL_CLIENT_PATH}:/home/node/app
    ports:
      - ${CLIENT_PORT}:80
    env_file:
      - ./client/deploy/.env
  database:
    image: onjin/alpine-postgres:9.6
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - ./api/deploy/.env
volumes:
  database:

networks:
  default:
    external:
      name: service-tier