version: '3.5'

services:
  express_api:
    container_name: express_api-dev
    environment:
      - POSTGRES_HOST=database
      - PORT=7770
      - VIRTUAL_HOST=dev.api.local
      - VIRTUAL_PORT=7770
      - ALLOW_ORIGIN=dev.client.local
  react_client:
    container_name: react_client-dev
    environment:
      - PORT=7771
      - VIRTUAL_HOST=dev.client.local
      - VIRTUAL_PORT=7770
  database:
    container_name: postgres_db-dev
    environment:
      - DB_PORT=5432