version: '3.5'

services:
  express_api:
    container_name: express_api-prod
    ports:
      - 7770:80
    env_file:
      - ./api/deploy/.env.prod
  react_client:
    container_name: react_client-production
    ports:
      - 7771:80
    environment:
      - NODE_ENV=production
      - PORT=7771
      - VIRTUAL_HOST=production.client.local
      - VIRTUAL_PORT=7771
    env_file:
      - ./client/deploy/.env.prod
  database:
    container_name: postgres_db-production
    ports:
      - 5432:5432
    env_file:
      - ./api/deploy/.env.prod